dask_yarn:
  build: .
  container_name: dask_yarn_container
  ports:
   - "8020:8020"
   - "50070:50070"
   - "8032:8032"
   - "8088:8088"
  entrypoint: bash /tmp/start.sh
  working_dir: /dask_yarn
  volumes:
   - ../:/dask_yarn
   - /Users/quasiben/Research/ContinuumDev/GitRepo/knit:/knit
  environment:
  - PYTHONPATH=/dask_yarn
